### ISSUE TITLE
$wgDiscourseSsoConsumer_LogoutDiscourse doesn't

### ISSUE THREAD

**Issue by uckelman** [centertap/DiscourseSsoConsumer#3]
I have
```
$wgDiscourseSsoConsumer_LogoutDiscourse = true;
```
in my `LocalSettings.php`.

Visiting Discourse without being logged in to Discourse or the wiki, logging in at Discourse, and then being automatically logged in to my wiki when visiting it (using `  $wgDiscourseSsoConsumer_AutoRelogin = true;`) works. Visiting the wiki when not logged in to Discourse redirects me to the Discourse login and then back to the wiki---that also works. So I have good reason to believe SSO generally is not broken.

When I log out of my wiki, I'm not logged out of Discourse---which is what that option is supposed to make happen.

**Comment by mdoggydog** [comment]
What version of Mediawiki and what version of PHP is your wiki using?  Also, does the browser report any obvious errors when clicking on the logout button (e.g., in Firefox's Web Console, etc)?

Logout is broken for my wiki, too, apparently (but my breakage may be different from yours).  I think the problem has to do with changes to the logout flow in MW that occurred sometime between 1.31 and 1.35 --- 1.31 was a simple follow-the-link GET request; 1.35 does a POST to the ApiLogout endpoint before navigating to the logout page, which is the first of several problems.  If so, I have a handle on how to fix it (via Discourse log_out API).

**Comment by uckelman** [comment]
MediaWiki 1.35.4 and PHP 7.4.25.

I suspect you're right w/r/t the logout flow---I ran into a similar problem with our old homebrew SSO steup when we upgraded to MW 1.35 from some very ancient version, and that was one of the reasons we junked our old SSO setup.

**Comment by mdoggydog** [comment]
Ok - this should be fixed in version 2.0.0.

You'll want to check out the upgrading notes in `RELEASE-NOTES.md` before upgrading.

`README.md` has instructions for setting up a log_out API key on the Discourse side.

**Comment by uckelman** [comment]
Thanks! I'll give this a try later this week and let you know how it goes.

**Comment by uckelman** [comment]
I only got back to this just this evening. I can confirm that using 2.0.1 with an API key that Discourse logouts work now. Thanks!
