### ISSUE TITLE
User::idFromName() removed in MediaWiki 1.41

### ISSUE THREAD

**Issue by Kelduum** [centertap/DiscourseSsoConsumer#7]
It looks like `User::idFromName()` has been removed in the current LTS, with the replacement being `UserIdentityLookup::getUserIdentityByName()`.

Attempting to install this on a current LTS version of MediaWiki looks like it's communicating with Discourse okay, but fails logging in.

**Comment by mdoggydog** [comment]
Thanks for noticing, @Kelduum !

This should now be fixed, in version 5.0.0.  (I had to bump the major-number because DiscourseSsoConsumer no longer works with MW 1.35 after this fix.)

Please confirm that this works with MW 1.41 now.   (I'm still developing/testing against 1.39 over here.)

**Comment by Kelduum** [comment]
>Please confirm that this works with MW 1.41 now

Yep, that seems to work perfectly now - awesome and very quick work!
